import "@fontsource/oswald/400.css";
import "@fontsource/oswald/700.css";
import type { Metadata } from "next";
import "./globals.css";
import { StateContext } from "@/context/StateProvicer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StateContext>
      <html lang="en">
        <head>
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet" />
        </head>
        <body className={`antialiased`}>{children}</body>
      </html>
    </StateContext>
  );
}
